# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI


on:

  push:

    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted 



    strategy:

      matrix:

        node-version: [18.x]

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/




    steps:

    - uses: actions/checkout@v2

    - name: Install yarn 

      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt-get update && sudo apt-get install -y yarn
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v3

      with:

        node-version: ${{ matrix.node-version }}

        cache: 'yarn'
        

    - run: yarn install --frozen-lockfile

    - run: yarn build
